// ============================================
// CONFIGURATION APPLIER
// ============================================
// This file automatically applies your config.js settings to the website
// DO NOT EDIT THIS FILE

document.addEventListener('DOMContentLoaded', function() {
  if (typeof CONFIG === 'undefined') {
    console.error('CONFIG not loaded. Make sure config.js is included before apply-config.js');
    return;
  }

  // Apply company name
  document.querySelectorAll('[data-config="company.name"]').forEach(el => {
    el.textContent = CONFIG.company.name;
  });

  // Apply tagline
  document.querySelectorAll('[data-config="company.tagline"]').forEach(el => {
    el.textContent = CONFIG.company.tagline;
  });

  // Apply phone numbers
  document.querySelectorAll('a[href^="tel:"]').forEach(el => {
    el.href = 'tel:' + CONFIG.company.phone;
    if (el.textContent.includes('Call')) {
      el.textContent = el.textContent.replace(/\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}/, CONFIG.company.phoneFormatted);
    } else if (el.textContent === 'Call') {
      // Keep as is for mobile button
    }
  });

  // Apply logo and favicon
  document.querySelectorAll('img[alt*="logo"]').forEach(el => {
    el.src = CONFIG.branding.logo;
  });

  const favicon = document.querySelector('link[rel="icon"]');
  if (favicon) {
    favicon.href = CONFIG.branding.favicon;
  }

  // Apply page titles
  const pageTitle = document.querySelector('title');
  if (pageTitle && window.location.pathname.includes('commercial')) {
    pageTitle.textContent = CONFIG.seo.titleCommercial;
  } else if (pageTitle) {
    pageTitle.textContent = CONFIG.seo.title;
  }

  // Configure forms
  const contactForm = document.querySelector('form[name="contact"]');
  if (contactForm && CONFIG.forms.provider) {
    switch(CONFIG.forms.provider.toLowerCase()) {
      case 'netlify':
        contactForm.setAttribute('data-netlify', 'true');
        contactForm.method = 'POST';
        contactForm.action = '';
        break;

      case 'formspree':
        if (CONFIG.forms.formspreeId) {
          contactForm.action = `https://formspree.io/f/${CONFIG.forms.formspreeId}`;
          contactForm.method = 'POST';
          contactForm.removeAttribute('data-netlify');
        } else {
          console.error('Formspree ID not configured in config.js');
        }
        break;

      case 'custom':
        if (CONFIG.forms.customEndpoint) {
          contactForm.action = CONFIG.forms.customEndpoint;
          contactForm.method = 'POST';
          contactForm.removeAttribute('data-netlify');
        } else {
          console.error('Custom endpoint not configured in config.js');
        }
        break;

      case 'none':
        console.warn('Form provider set to "none" - form will not submit');
        contactForm.addEventListener('submit', function(e) {
          e.preventDefault();
          alert('Form submission is not configured. Please update config.js');
        });
        break;
    }
  }

  console.log('✓ Configuration applied successfully');
});
